import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import { cleanupTempDirs, tempDir, writeScopeFixture } from "../test-support/index.js";
import { buildAutoGeneratedBanner, renderRoadmap, renderSpec } from "./index.js";

afterAll(() => {
  cleanupTempDirs();
});

function emptyProject(): string {
  const root = tempDir("render-test-");
  for (const folder of ["proposed", "pending", "active", "completed", "cancelled"]) {
    mkdirSync(join(root, "xbrief", folder), { recursive: true });
  }
  return root;
}

describe("buildAutoGeneratedBanner", () => {
  it("is exactly 4 lines naming purpose, source of truth, and the regenerate command", () => {
    const banner = buildAutoGeneratedBanner({
      purpose: "p",
      sourceOfTruth: "s",
      regenerateTarget: "x",
    });
    const lines = banner.split("\n");
    expect(lines).toHaveLength(4);
    expect(lines[0]).toContain("AUTO-GENERATED by canon render");
    expect(lines[1]).toContain("Purpose: p");
    expect(lines[2]).toContain("Source of truth: s");
    expect(lines[3]).toContain("Regenerate with: task render x");
  });
});

describe("renderRoadmap: golden output", () => {
  it("writes one section per lifecycle folder in deterministic filename order", () => {
    const root = emptyProject();
    writeScopeFixture(root, "active", "2026-01-02-second.xbrief.json", {
      title: "Second story",
      status: "running",
      "x-canonical/dependencies": ["2026-01-01-first.xbrief.json"],
      references: [
        {
          uri: "https://github.com/x/y/issues/9",
          type: "x-xbrief/github-issue",
          "x-canonical/trust": "external",
        },
      ],
    });
    writeScopeFixture(root, "active", "2026-01-01-first.xbrief.json", {
      title: "First story",
      status: "blocked",
    });
    writeScopeFixture(root, "proposed", "2026-01-03-candidate.xbrief.json", {
      title: "Candidate",
    });

    const result = renderRoadmap(root);
    expect(result.ok).toBe(true);
    expect(result.code).toBe(0);

    const written = readFileSync(join(root, "ROADMAP.md"), "utf8");
    expect(written.split("\n").slice(0, 4)).toEqual([
      "<!-- AUTO-GENERATED by canon render -->",
      "<!-- Purpose: point-in-time view of scope lifecycle state -->",
      "<!-- Source of truth: xbrief/**/*.xbrief.json -->",
      "<!-- Regenerate with: task render roadmap -->",
    ]);
    expect(written).toContain("## Proposed");
    expect(written).toContain("## Active");
    expect(written).toContain("| Candidate | proposed | - | - |");
    // filename-sorted: first's row precedes second's row within Active.
    const firstIdx = written.indexOf("| First story |");
    const secondIdx = written.indexOf("| Second story |");
    expect(firstIdx).toBeGreaterThan(-1);
    expect(secondIdx).toBeGreaterThan(firstIdx);
    expect(written).toContain(
      "| Second story | running | [https://github.com/x/y/issues/9](https://github.com/x/y/issues/9) | 2026-01-01-first.xbrief.json |",
    );
    expect(written).toContain("| First story | blocked | - | - |");
  });

  it("escapes pipes and newlines in data-derived cells so rows cannot break the table", () => {
    const root = emptyProject();
    writeScopeFixture(root, "proposed", "2026-01-04-tricky.xbrief.json", {
      title: "Fix a | b\nparsing",
    });

    const result = renderRoadmap(root);
    expect(result.ok).toBe(true);

    const written = readFileSync(join(root, "ROADMAP.md"), "utf8");
    expect(written).toContain("| Fix a \\| b parsing | proposed | - | - |");
    // every non-header line inside the tables stays a single row
    expect(written).not.toContain("\nparsing");
  });

  it("--check passes when the committed file matches the regenerated output", () => {
    const root = emptyProject();
    writeScopeFixture(root, "proposed", "2026-01-01-a.xbrief.json", { title: "A" });
    const write = renderRoadmap(root);
    expect(write.ok).toBe(true);

    const check = renderRoadmap(root, { check: true });
    expect(check).toEqual({
      ok: true,
      code: 0,
      message: "ROADMAP.md up to date",
      path: check.path,
    });
  });

  it("--check fails (violation, code 1) when the committed file is missing", () => {
    const root = emptyProject();
    const check = renderRoadmap(root, { check: true });
    expect(check.ok).toBe(false);
    expect(check.code).toBe(1);
    expect(check.message).toContain("ROADMAP.md missing");
  });

  it("--check fails (violation, code 1) when the committed file is stale", () => {
    const root = emptyProject();
    writeScopeFixture(root, "proposed", "2026-01-01-a.xbrief.json", { title: "A" });
    renderRoadmap(root);
    writeScopeFixture(root, "proposed", "2026-01-02-b.xbrief.json", { title: "B" });

    const check = renderRoadmap(root, { check: true });
    expect(check.ok).toBe(false);
    expect(check.code).toBe(1);
    expect(check.message).toContain("ROADMAP.md is stale");
  });
});

describe("renderSpec: golden output", () => {
  it("renders title as H1 and narrative string fields as H2 sections, items as a numbered list", () => {
    const root = emptyProject();
    writeFileSync(
      join(root, "xbrief", "spec.xbrief.json"),
      JSON.stringify({
        xBRIEFInfo: { version: "0.8" },
        plan: {
          title: "My Spec",
          narratives: { Overview: "What this is.", Requirements: "What it must do." },
          items: ["first requirement", "second requirement"],
        },
      }),
    );

    const result = renderSpec(root);
    expect(result.ok).toBe(true);
    const written = readFileSync(join(root, "SPEC.md"), "utf8");
    expect(written.split("\n").slice(0, 4)).toEqual([
      "<!-- AUTO-GENERATED by canon render -->",
      "<!-- Purpose: human-readable requirements view -->",
      "<!-- Source of truth: xbrief/spec.xbrief.json -->",
      "<!-- Regenerate with: task render spec -->",
    ]);
    expect(written).toContain("# My Spec");
    expect(written).toContain("## Overview");
    expect(written).toContain("What this is.");
    expect(written).toContain("## Requirements");
    expect(written).toContain("1. first requirement");
    expect(written).toContain("2. second requirement");
  });

  it("returns a violation (code 1) when xbrief/spec.xbrief.json is absent", () => {
    const root = emptyProject();
    const result = renderSpec(root);
    expect(result).toEqual({ ok: false, code: 1, message: "xbrief/spec.xbrief.json missing" });
  });

  it("returns a misconfig (code 2) when spec.xbrief.json is not a JSON object", () => {
    const root = emptyProject();
    writeFileSync(join(root, "xbrief", "spec.xbrief.json"), "[1, 2]");
    const result = renderSpec(root);
    expect(result.ok).toBe(false);
    expect(result.code).toBe(2);
    expect(result.message).toContain("not a JSON object");
  });

  it("returns a misconfig (code 2) when spec.xbrief.json lacks a plan object", () => {
    const root = emptyProject();
    writeFileSync(join(root, "xbrief", "spec.xbrief.json"), JSON.stringify({ title: "legacy" }));
    const result = renderSpec(root);
    expect(result.ok).toBe(false);
    expect(result.code).toBe(2);
    expect(result.message).toContain("not an xBRIEF document");
  });

  it("spec --check passes when the committed file matches the regenerated output", () => {
    const root = emptyProject();
    writeFileSync(
      join(root, "xbrief", "spec.xbrief.json"),
      JSON.stringify({
        xBRIEFInfo: { version: "0.8" },
        plan: { title: "S", narratives: { Overview: "o" } },
      }),
    );
    renderSpec(root);
    const check = renderSpec(root, { check: true });
    expect(check).toEqual({ ok: true, code: 0, message: "SPEC.md up to date", path: check.path });
  });

  it("spec --check fails (violation, code 1) when the committed file is stale", () => {
    const root = emptyProject();
    writeFileSync(
      join(root, "xbrief", "spec.xbrief.json"),
      JSON.stringify({
        xBRIEFInfo: { version: "0.8" },
        plan: { title: "S", narratives: { Overview: "o" } },
      }),
    );
    renderSpec(root);
    writeFileSync(
      join(root, "xbrief", "spec.xbrief.json"),
      JSON.stringify({
        xBRIEFInfo: { version: "0.8" },
        plan: { title: "S2", narratives: { Overview: "o" } },
      }),
    );
    const check = renderSpec(root, { check: true });
    expect(check.ok).toBe(false);
    expect(check.code).toBe(1);
    expect(check.message).toContain("SPEC.md is stale");
  });
});
