import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { atomicWriteText } from "../fs/contained-write.js";
import type { GateExitCode, LifecycleFolder, ScopeDoc } from "../types/index.js";
import { LIFECYCLE_FOLDERS, SPEC_BRIEF_NAME, scopeDependencies } from "../types/index.js";
import { listScopes, readScope } from "../xbrief/brief-io.js";

/**
 * Generated-view renderers (content/canonical-tasks.md `render`):
 * `roadmap` -> ROADMAP.md from the lifecycle folders, `spec` -> SPEC.md from
 * xbrief/spec.xbrief.json. Both open with a 4-line AUTO-GENERATED banner and
 * support `--check` (regenerate in memory, byte-compare against the committed file).
 */

export interface AutoGeneratedBannerOptions {
  readonly purpose: string;
  readonly sourceOfTruth: string;
  readonly regenerateTarget: string;
}

/** 4-line AUTO-GENERATED banner every render output opens with. */
export function buildAutoGeneratedBanner(opts: AutoGeneratedBannerOptions): string {
  return [
    "<!-- AUTO-GENERATED by canon render -->",
    `<!-- Purpose: ${opts.purpose} -->`,
    `<!-- Source of truth: ${opts.sourceOfTruth} -->`,
    `<!-- Regenerate with: task render ${opts.regenerateTarget} -->`,
  ].join("\n");
}

export interface RenderOptions {
  /** Regenerate in memory and byte-compare against the committed file instead of writing. */
  readonly check?: boolean;
}

export interface RenderResult {
  readonly ok: boolean;
  readonly code: GateExitCode;
  readonly message: string;
  /** Absolute path written (write mode) or checked (check mode) on success. */
  readonly path?: string;
}

function applyRender(
  projectRoot: string,
  relPath: string,
  content: string,
  opts: RenderOptions,
  target: string,
): RenderResult {
  if (opts.check === true) {
    const abs = join(projectRoot, relPath);
    if (!existsSync(abs)) {
      return {
        ok: false,
        code: 1,
        message: `${relPath} missing -- regenerate with: task render ${target}`,
      };
    }
    let existing: string;
    try {
      existing = readFileSync(abs, "utf8");
    } catch (err) {
      return { ok: false, code: 2, message: `cannot read ${relPath}: ${(err as Error).message}` };
    }
    if (existing !== content) {
      return {
        ok: false,
        code: 1,
        message: `${relPath} is stale -- regenerate with: task render ${target}`,
      };
    }
    return { ok: true, code: 0, message: `${relPath} up to date`, path: abs };
  }
  const abs = atomicWriteText(projectRoot, relPath, content);
  return { ok: true, code: 0, message: `wrote ${relPath}`, path: abs };
}

const ROADMAP_SECTION_TITLES: Readonly<Record<LifecycleFolder, string>> = {
  proposed: "Proposed",
  pending: "Pending",
  active: "Active",
  completed: "Completed",
  cancelled: "Cancelled",
};

function firstIssueOriginLink(scope: ScopeDoc): string {
  const ref = (scope.plan.references ?? []).find((r) => r.type === "x-xbrief/github-issue");
  return ref === undefined ? "-" : `[${ref.uri}](${ref.uri})`;
}

function dependenciesCell(scope: ScopeDoc): string {
  const deps = scopeDependencies(scope);
  return deps.length > 0 ? deps.join(", ") : "-";
}

function buildRoadmapContent(projectRoot: string): string {
  const rowsByFolder = new Map<LifecycleFolder, string[]>(LIFECYCLE_FOLDERS.map((f) => [f, []]));
  for (const ref of listScopes(projectRoot)) {
    const read = readScope(ref.path);
    if (!read.ok) {
      continue;
    }
    const scope = read.scope;
    const row = `| ${scope.plan.title} | ${scope.plan.status} | ${firstIssueOriginLink(scope)} | ${dependenciesCell(scope)} |`;
    rowsByFolder.get(ref.folder)?.push(row);
  }

  const lines: string[] = [
    buildAutoGeneratedBanner({
      purpose: "point-in-time view of scope lifecycle state",
      sourceOfTruth: "xbrief/**/*.xbrief.json",
      regenerateTarget: "roadmap",
    }),
    "",
    "# Roadmap",
  ];
  for (const folder of LIFECYCLE_FOLDERS) {
    lines.push("", `## ${ROADMAP_SECTION_TITLES[folder]}`, "");
    lines.push("| Title | Status | Origin | Dependencies |");
    lines.push("| --- | --- | --- | --- |");
    for (const row of rowsByFolder.get(folder) ?? []) {
      lines.push(row);
    }
  }
  lines.push("");
  return lines.join("\n");
}

/** Generate ROADMAP.md from the lifecycle folders under xbrief/. */
export function renderRoadmap(projectRoot: string, opts: RenderOptions = {}): RenderResult {
  return applyRender(projectRoot, "ROADMAP.md", buildRoadmapContent(projectRoot), opts, "roadmap");
}

interface SpecPlan {
  readonly title?: string;
  readonly narratives?: Record<string, unknown>;
  readonly items?: readonly unknown[];
}

type ReadSpecResult =
  | { readonly ok: true; readonly spec: SpecPlan }
  | { readonly ok: false; readonly code: GateExitCode; readonly message: string };

const SPEC_REL = `xbrief/${SPEC_BRIEF_NAME}`;

function readSpecBrief(projectRoot: string): ReadSpecResult {
  const specPath = join(projectRoot, "xbrief", SPEC_BRIEF_NAME);
  if (!existsSync(specPath)) {
    return { ok: false, code: 1, message: `${SPEC_REL} missing` };
  }
  try {
    const parsed: unknown = JSON.parse(readFileSync(specPath, "utf8"));
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
      return { ok: false, code: 2, message: `${SPEC_REL}: not a JSON object` };
    }
    const plan = (parsed as Record<string, unknown>).plan;
    if (typeof plan !== "object" || plan === null || Array.isArray(plan)) {
      return {
        ok: false,
        code: 2,
        message: `${SPEC_REL}: not an xBRIEF document (missing plan object)`,
      };
    }
    return { ok: true, spec: plan as SpecPlan };
  } catch (err) {
    return {
      ok: false,
      code: 2,
      message: `${SPEC_REL}: invalid JSON (${(err as Error).message})`,
    };
  }
}

function itemLabel(item: unknown): string {
  if (typeof item === "string") {
    return item;
  }
  if (typeof item === "object" && item !== null) {
    const title = (item as Record<string, unknown>).title;
    if (typeof title === "string" && title !== "") {
      return title;
    }
  }
  return JSON.stringify(item);
}

function buildSpecContent(spec: SpecPlan): string {
  const lines: string[] = [
    buildAutoGeneratedBanner({
      purpose: "human-readable requirements view",
      sourceOfTruth: SPEC_REL,
      regenerateTarget: "spec",
    }),
    "",
    `# ${spec.title ?? "Spec"}`,
  ];
  const narratives = spec.narratives ?? {};
  for (const [key, value] of Object.entries(narratives)) {
    if (typeof value === "string") {
      lines.push("", `## ${key}`, "", value);
    }
  }
  const items = spec.items ?? [];
  if (items.length > 0) {
    lines.push("", "## Items", "");
    items.forEach((item, i) => {
      lines.push(`${i + 1}. ${itemLabel(item)}`);
    });
  }
  lines.push("");
  return lines.join("\n");
}

/** Generate SPEC.md from xbrief/spec.xbrief.json. A missing spec doc is a violation, not a config error. */
export function renderSpec(projectRoot: string, opts: RenderOptions = {}): RenderResult {
  const read = readSpecBrief(projectRoot);
  if (!read.ok) {
    return { ok: false, code: read.code, message: read.message };
  }
  return applyRender(projectRoot, "SPEC.md", buildSpecContent(read.spec), opts, "spec");
}
