/**
 * Build-channel constants baked at compile time.
 * Regenerated by `scripts/write-build-info.mjs` (see package.json `prebuild`).
 */
export {
  BUILD_CHANNEL,
  type BuildChannel,
  COLLECTION_BASE_URL,
  COLLECTION_ENV,
} from "./build-info.generated.js";
