/* AUTO-GENERATED by scripts/write-build-info.mjs — do not edit by hand. */
export type BuildChannel = "staging" | "production";

export const BUILD_CHANNEL: BuildChannel = "staging";
export const COLLECTION_BASE_URL: string = "https://api.deft-staging.co/collector";
export const COLLECTION_ENV: string = "staging";
